# Generated by Django 2.2.3 on 2019-07-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Оцінка', 'verbose_name_plural': 'Оцінки'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'Клас', 'verbose_name_plural': 'Класи'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Учень', 'verbose_name_plural': 'Учні'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Вчитель', 'verbose_name_plural': 'Вчителі'},
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
